# Generated by Django 5.0.6 on 2024-07-20 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='not_completed_tasks_count',
            new_name='notcompleted_tasks_count',
        ),
    ]
